project:
  version: 1.0

server:
  port: 8087
spring:
  application:
    name: user
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS TESTDB #DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE #jdbc:h2:file:./data/testdb #jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: admin
    password: password
    initialization-mode: always
    platform: h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
      spring:
        settings:
          web-allow-others: true


logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    operations-sorter: alpha
    tags-sorter: alpha
